package com.bbbdem.koha.module.my_account.purchase_suggestions.model

import com.google.gson.annotations.SerializedName

data class SuggestionListResponseModel(@SerializedName("accepted_by"             ) var acceptedBy           : String?  = null,
                                       @SerializedName("accepted_date"           ) var acceptedDate         : String?  = null,
                                       @SerializedName("archived"                ) var archived             : Boolean? = null,
                                       @SerializedName("author"                  ) var author               : String?  = null,
                                       @SerializedName("biblio_id"               ) var biblioId             : String?  = null,
                                       @SerializedName("budget_id"               ) var budgetId             : String?  = null,
                                       @SerializedName("collection_title"        ) var collectionTitle      : String?  = null,
                                       @SerializedName("copyright_date"          ) var copyrightDate        : Int?     = null,
                                       @SerializedName("currency"                ) var currency             : String?  = null,
                                       @SerializedName("isbn"                    ) var isbn                 : String?  = null,
                                       @SerializedName("item_price"              ) var itemPrice            : String?  = null,
                                       @SerializedName("item_type"               ) var itemType             : String?  = null,
                                       @SerializedName("last_status_change_by"   ) var lastStatusChangeBy   : String?  = null,
                                       @SerializedName("last_status_change_date" ) var lastStatusChangeDate : String?  = null,
                                       @SerializedName("library_id"              ) var libraryId            : String?  = null,
                                       @SerializedName("managed_by"              ) var managedBy            : String?  = null,
                                       @SerializedName("managed_date"            ) var managedDate          : String?  = null,
                                       @SerializedName("note"                    ) var note                 : String?  = null,
                                       @SerializedName("patron_reason"           ) var patronReason         : String?  = null,
                                       @SerializedName("publication_place"       ) var publicationPlace     : String?  = null,
                                       @SerializedName("publication_year"        ) var publicationYear      : String?  = null,
                                       @SerializedName("publisher_code"          ) var publisherCode        : String?  = null,
                                       @SerializedName("quantity"                ) var quantity             : String?  = null,
                                       @SerializedName("reason"                  ) var reason               : String?  = null,
                                       @SerializedName("rejected_by"             ) var rejectedBy           : String?  = null,
                                       @SerializedName("rejected_date"           ) var rejectedDate         : String?  = null,
                                       @SerializedName("staff_note"              ) var staffNote            : String?  = null,
                                       @SerializedName("status"                  ) var status               : String?  = null,
                                       @SerializedName("suggested_by"            ) var suggestedBy          : Int?     = null,
                                       @SerializedName("suggestion_date"         ) var suggestionDate       : String?  = null,
                                       @SerializedName("suggestion_id"           ) var suggestionId         : Int?     = null,
                                       @SerializedName("timestamp"               ) var timestamp            : String?  = null,
                                       @SerializedName("title"                   ) var title                : String?  = null,
                                       @SerializedName("total_price"             ) var totalPrice           : String?  = null,
                                       @SerializedName("volume_desc"             ) var volumeDesc           : String?  = null,
                                       var isChecked           : Boolean  = false)
