package com.bbbdem.koha.module.my_account.summary.model

import com.bbbdem.koha.module.dashboard.model.ItemListOfBookResponseModel
import com.google.gson.annotations.SerializedName

data class BookDetailResponseModel(@SerializedName("abstract"            ) var abstract          : String?  = "",
                                   @SerializedName("age_restriction"     ) var ageRestriction    : String?  = "",
                                   @SerializedName("author"              ) var author            : String?  = "",
                                   @SerializedName("biblio_id"           ) var biblioId          : Int?     = null,
                                   @SerializedName("cn_class"            ) var cnClass           : String?  = "",
                                   @SerializedName("cn_item"             ) var cnItem            : String?  = "",
                                   @SerializedName("cn_sort"             ) var cnSort            : String?  = "",
                                   @SerializedName("cn_source"           ) var cnSource          : String?  = "",
                                   @SerializedName("cn_suffix"           ) var cnSuffix          : String?  = "",
                                   @SerializedName("collection_issn"     ) var collectionIssn    : String?  = "",
                                   @SerializedName("collection_title"    ) var collectionTitle   : String?  = "",
                                   @SerializedName("collection_volume"   ) var collectionVolume  : String?  = "",
                                   @SerializedName("copyright_date"      ) var copyrightDate     : String?  = "",
                                   @SerializedName("creation_date"       ) var creationDate      : String?  = "",
                                   @SerializedName("ean"                 ) var ean               : String?  = "",
                                   @SerializedName("edition_statement"   ) var editionStatement  : String?  = "",
                                   @SerializedName("framework_id"        ) var frameworkId       : String?  = "",
                                   @SerializedName("illustrations"       ) var illustrations     : String?  = "",
                                   @SerializedName("isbn"                ) var isbn              : String?  = "",
                                   @SerializedName("issn"                ) var issn              : String?  = "",
                                   @SerializedName("item_type"           ) var itemType          : String?  = "",
                                   @SerializedName("lc_control_number"   ) var lcControlNumber   : String?  = "",
                                   @SerializedName("material_size"       ) var materialSize      : String?  = "",
                                   @SerializedName("medium"              ) var medium            : String?  = "",
                                   @SerializedName("notes"               ) var notes             : String?  = "",
                                   @SerializedName("number"              ) var number            : String?  = "",
                                   @SerializedName("pages"               ) var pages             : String?  = "",
                                   @SerializedName("part_name"           ) var partName          : String?  = "",
                                   @SerializedName("part_number"         ) var partNumber        : String?  = "",
                                   @SerializedName("publication_place"   ) var publicationPlace  : String?  = "",
                                   @SerializedName("publication_year"    ) var publicationYear   : String?  = "",
                                   @SerializedName("publisher"           ) var publisher         : String?  = "",
                                   @SerializedName("serial"              ) var serial            : Boolean? = null,
                                   @SerializedName("serial_total_issues" ) var serialTotalIssues : String?  = "",
                                   @SerializedName("series_title"        ) var seriesTitle       : String?  = "",
                                   @SerializedName("subtitle"            ) var subtitle          : String?  = "",
                                   @SerializedName("timestamp"           ) var timestamp         : String?  = "",
                                   @SerializedName("title"               ) var title             : String?  = "",
                                   @SerializedName("uniform_title"       ) var uniformTitle      : String?  = "",
                                   @SerializedName("url"                 ) var url               : String?  = "",
                                   @SerializedName("volume"              ) var volume            : String?  = "",
                                   @SerializedName("volume_date"         ) var volumeDate        : String?  = "",
                                   @SerializedName("volume_description"  ) var volumeDescription : String?  = "",
                                   var bookDetailModel: BookDetailModel?=null,
                                   var itemDetailResponseModel: ItemDetailResponseModel?=null,
                                   var itemListOfBookResponseModel : List<ItemListOfBookResponseModel>?=null)
